#+ summary: Popular performers that are related (4 types of relations)
#+ endpoint: https://api.data.muziekweb.nl/datasets/MuziekwebOrganization/Muziekweb/services/Muziekweb/sparql
prefix vocab: <https://data.muziekweb.nl/vocab/>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix skos: <http://www.w3.org/2004/02/skos/core#>
select distinct ?s1 ?name1 ?s2 ?name2 ?relation
where {
  values ?relation {
    vocab:related
    vocab:influencedBy
    vocab:contemporary
    vocab:seeAlso
  }
  ?s1 rdf:type vocab:PopularPerformer ;
    skos:prefLabel ?name1 .
  ?s2 rdf:type vocab:PopularPerformer ;
    skos:prefLabel ?name2 .
  ?s1 ?relation ?s2
}
limit 100
