#+ summary: Query to get unique genres in muziekweb in EN
#+ endpoint: https://api.data.muziekweb.nl/datasets/MuziekwebOrganization/Muziekweb/services/Muziekweb/sparql
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix vocab: <https://data.muziekweb.nl/vocab/>

select DISTINCT ?genre ?genreLabel where {
  ?genre rdf:type <https://data.muziekweb.nl/vocab/Genre> .
  ?genre rdfs:label ?genreLabel
   FILTER (lang(?genreLabel) = "en")
} 
GROUP BY ?genre ?genreLabel
ORDER BY ?genreLabel